apiVersion: v1
kind: ConfigMap
metadata:
  name: mail-sender-cm
  labels:
    kelompok: yang-belum-siap
    app: mail-sender
    type: config-map
data:
  smtp_host: smtp.gmail.com
  smtp_port: "587"
  smtp_secure: "false"
  app_port: "8082"
