apiVersion: v1
kind: Service
metadata:
  name: mail-sender-np
  labels:
    kelompok: yang-belum-siap
    app: mail-sender
    type: node-port
spec:
  type: NodePort
  selector:
    app: mail-sender
    type: pods
  ports:
    - port: 8080
      targetPort: 8082
      nodePort: 30001
